workflows:
  react-native-android:
    name: Build Android APK
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        ANDROID_APP_ID: "com.yourapp.name" # Replace with your package name
      flutter: stable
      xcode: latest
    scripts:
      - name: Install Dependencies
        script: |
          npm install
      - name: Build Android APK
        script: |
          cd android && ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - "your-email@example.com"  # Replace with your email
