workflows:
  react-native-android:
    name: React Native Android Build
    max_build_duration: 60
    environment:
      vars:
        JAVA_VERSION: 17
        GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m"
      java: 17
      node: latest
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Clean Gradle
        script: cd android && ./gradlew clean
      - name: Build APK
        script: cd android && ./gradlew assembleRelease --stacktrace
    artifacts:
      - android/app/build/outputs/**/*.apk
